services:
  redis:
    image: redis:latest
    container_name: local-redis
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:latest 
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" 
      - "9093:9093" 
    environment:
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk  
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9093,EXTERNAL://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9093,EXTERNAL://localhost:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-kafka-logs"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999 
      KAFKA_JMX_HOSTNAME: localhost 